const mongoose = require("mongoose");

const conversationSchema = new mongoose.Schema(
  {
    botId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Bot",
      required: true,
      index: true,
    },

    // Generated by the widget on load (e.g. uuid stored in sessionStorage)
    sessionId: {
      type: String,
      required: true,
      index: true,
    },

    // LLM-generated short title from first message
    // e.g. "Refund policy question"
    label: {
      type: String,
      default: null,
    },

    // Resolved/unresolved — null means not yet classified by LLM
    isResolved: {
      type: Boolean,
      default: null,
    },
    resolutionReason: {
      type: String,
      default: null, // LLM's reasoning
    },

    messageCount: {
      type: Number,
      default: 0,
    },
    lastMessageAt: {
      type: Date,
      default: Date.now,
    },
    endedAt: {
      type: Date,
      default: null, // set when widget session closes
    },
  },
  { timestamps: true }
);

// Index for dashboard recent activity queries
conversationSchema.index({ botId: 1, lastMessageAt: -1 });

module.exports = mongoose.model("Conversation", conversationSchema);
